#!/bin/sh -l
#PBS -o out.$PBS_JOBID
#PBS -e err.$PBS_JOBID
#PBS -N testrun
#PBS -A nems
#PBS -q debug
#PBS -l procs=24
#PBS -l walltime=00:10:00

set -x

export MPI_TYPE_DEPTH=20
export OMP_NUM_THREADS=1
export ESMF_RUNTIME_COMPLIANCECHECK=OFF

source /etc/profile
module use /scratch4/NCEPDEV/nems/save/Gerhard.Theurich/Modulefiles
module load intel impi/5.1.1.109 netcdf esmf/7.1.0bs07-g-IMPI5.1.1.109
module list
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/apps/hdf5/1.8.14-intel/lib/

pwd

echo "Model started:  " `date`

rm -rf ~/scratch/testrun3
mkdir ~/scratch/testrun3
cp -r /scratch4/NCEPDEV/ocean/noscrub/Fei.Liu/MOM6_Ocean_Only_Input/* ~/scratch/testrun3/
#cp /scratch4/NCEPDEV/ocean/noscrub/Fei.Liu/MOM6_JD/build/intel/ocean_only/repro/MOM6 ~/scratch/testrun3
cp /scratch4/NCEPDEV/ocean/noscrub/Fei.Liu/MOM6_OCEAN_MODEL/build/intel/ocean_only/repro/MOM6 ~/scratch/testrun3
cd ~/scratch/testrun3
rm -rf OUTPUT
rm -rf RESTART
mkdir OUTPUT
mkdir RESTART
mpirun  -prepend-rank -np $PBS_NP ./MOM6

echo "Model ended:    " `date`

exit

